mindee/documents/invoice.py, mindee/documents/receipt.py, tests/documents/test_invoice.py, tests/documents/test_receipt.py
Fixing [issue #2](https://github.com/publicMindee/mindee-api-python/issues/2)
There was no check ensuring that tax rates were non null before using them in reconstruction method.
https://github.com/publicMindee/mindee-api-python/issues/2
Added test for Invoice and Receipt classes, by constructing objects with null rates and testing 
the constructions don't raise an error.
=> Fix issue #2

CHANGELOG.md, mindee/documents/invoice.py
Total tax reconstruction now uses also total including and total excluding for invoice
We were using only the tax lines for reconstructing the total tax. In case there is no tax line in the invoice we can use the data for total including and excluding to retrieve the information.
Fully tested, as part as the invoice testing.
=> chg: :sparkles: Invoice total tax better coverage

CHANGELOG.md, README.md, mindee/documents/financial_document.py, requirements.dev.txt, tests/documents/test_financial_doc.py, tests/documents/test_invoice.py
Fix for FinancialDocument API
The Invoice version used for FinanicialDocument was "v1" and it led to errors.
The tax rate can now be None with the V2, fixed this error.
Fully tested
- [ x] Docs change / refactoring / dependency upgrade
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
=> :bug: Fix financial doc

README.md
Fixes: #6  
- Make `receipts` singular
Fixes: #6  
- Make `receipts` singular
See linked issue.
=> fix: :memo: :bug: receipts -> receipt in parameter name & doc

tests/test_inputs.py
Fix a bug in inputs test. 
The file cursor was not re-initialized causing the .read() method to return b""
=> Fix broken inputs test

mindee/inputs.py, requirements.txt
- use `page.get_cdrawings()` to check if PDF page has any "path" within in addition to image or text to check if page is blank or not.
- upgrade pymupdf to 1.18.17 (to access the newest and fasted method `page.get_cdrawings()`
- remove unused parameter in `check_if_document_is_empty` function.
Some PDF files are recognized as blank (zero page) #25
=> Fix blank pdf - use pages.get_cdrawings()

mindee/__init__.py, mindee/http.py, mindee/versions.py, setup.py
Add a `User-Agent` header with SDK and Python versions, and platform.
Add a new file `versions.py` allowing retrieving this info.
Having this info allows us to better serve our API users by letting us know which versions are in use.
=> chg: :sparkles: add user-agent header with SDK and Python versions

.github/workflows/linting.yml, mindee/__init__.py, mindee/documents/__init__.py, mindee/documents/car_plate.py, mindee/documents/financial_document.py, mindee/documents/invoice.py, mindee/documents/passport.py, mindee/documents/receipt.py, mindee/fields/__init__.py, mindee/http.py, mindee/inputs.py, mindee/versions.py, pyproject.toml, setup.py
Add mypy for type checking and pylint for static analysis.
Do some very basic improvements just to make sure everything works.
This will avoid bugs, hopefully!
=> Add mypy pylint

mindee/documents/financial_document.py, mindee/documents/invoice.py, mindee/documents/passport.py, mindee/documents/receipt.py, mindee/fields/__init__.py, tests/documents/test_financial_doc.py, tests/documents/test_invoice.py, tests/documents/test_receipt.py, tests/fields/test_amount.py, tests/fields/test_date.py, tests/fields/test_field.py, tests/fields/test_locale.py, tests/fields/test_orientation.py, tests/fields/test_payment_details.py, tests/fields/test_tax.py
API response was changed, `probability` is now `confidence`, we need to update the SDK.
We are **not** changing the `Field.probability` in the SDK for backwards compatibility.
This will be changed in the upcoming v2.
New unit tests added, all tests updated.
=> fix: :bug: fix probabilities not loaded from API

mindee/__main__.py, mindee/client.py, mindee/documents/financial_document.py, tests/documents/test_document.py, tests/test_cli.py
=> :bug: fix sending financial document via the CLI

setup.py
Implement PEP 561 using the `py.typed` marker file.
https://www.python.org/dev/peps/pep-0561/
This fixes the mypy error:
```
Skipping analyzing "mindee": module is installed, but missing library stubs or py.typed marker
```
=> :label: declare type info to mypy (PEP 561)

.pre-commit-config.yaml, .pylintrc, pyproject.toml, setup.cfg, setup.py, tests/test_pkg_versions.py
Add the `pre-commit` tool and configure it for our code style.
https://pre-commit.com/
Moved most info from `setup.py` to `setup.cfg` because the future is now ;-)
=> :technologist: add pre-commit to ensure proper code formatting

mindee/client.py, mindee/documents/base.py, mindee/documents/custom_document.py, mindee/documents/financial_document.py, mindee/documents/invoice.py, mindee/documents/passport.py, mindee/documents/receipt.py, mindee/http.py, mindee/inputs.py, tests/test_client.py
Add the option `close_file` when parsing a document to specify if the file pointer should be closed after processing.
Send the same file to two endpoints without needing to reopen:
```
async def parse_doc(upload: UploadFile):
"""Parse a document."""
doc = mindee_client.doc_from_bytes(
upload.file.read(),
upload.filename,
)
custom_response = doc.parse("custom_doc", close_file=False)
invoice_response = doc.parse("invoice", close_file=True)
```
Add unit test.
=> :sparkles: Allow specifying file closing behavior

mindee/fields/amount.py, mindee/fields/base.py, mindee/fields/date.py, mindee/fields/locale.py, mindee/fields/orientation.py, mindee/fields/payment_details.py, mindee/geometry.py, tests/test_geometry.py
API's `polygon` property is now set to the new field property `polygon`.
Existing field property `bbox` is now an actual calculated bounding box.
For OTS products this will have no effect, since currently polygons are always rectangular bounding boxes.
Will be useful when we transition custom docs to object fields.
Required work for Cropper feature and having classes in the custom document response.
New unit tests.
=> :sparkles: add real bounding box

mindee/documents/bank_check.py, mindee/documents/custom_document.py, mindee/documents/financial_document.py, mindee/documents/invoice.py, mindee/documents/passport.py, mindee/documents/receipt.py
We should never use mutable defaults in class definitions.
These work the same way as mutable defaults in function definitions, but are not checked by mypy it seems.
Consider using dataclasses in a future version.
https://docs.python.org/3/library/dataclasses.html#mutable-default-values
=> :bug: should never use mutable defaults in class definitions

README.md, mindee/client.py, mindee/response.py, tests/test_response.py
This feature adds needless complexity to using the library, and has been dropped from Java and Node.js libraries.
Also first step in providing generic functions with proper type information.
Completely backwards compatible.
Added unit tests.
=> :wastebasket: deprecate setting singular and plural names for docs

mindee/fields/base.py, mindee/geometry.py, tests/test_geometry.py
Add a function to get the bounding box of multiple polygons
Useful for certain user functions like line items.
Unit test added.
=> :sparkles: add getting bounding box for multiple polygons

mindee/fields/api_builder.py, mindee/fields/base.py, tests/documents/test_custom_v1.py, tests/documents/test_invoice_v3.py, tests/documents/test_passport_v1.py, tests/documents/test_receipt_v3.py, tests/documents/test_receipt_v4.py
The `page_id` is almost always returned by the API.
Use this to set the property `page_n` of  various fields classes, when they are linked to a `Document`.
Added unit tests.
=> :bug: page_n should always be set when available

README.md, mindee/documents/config.py, mindee/endpoints.py, tests/utils.py
Allow setting the request timeout from  `MINDEE_REQUEST_TIMEOUT` envvar
Manual testing :-(
=> :sparkles: allow setting timeout value from env

README.md, docs/guide/python-api-builder.md, docs/guide/python-cli.md, docs/guide/python-getting-started.md, docs/guide/python-invoice-ocr.md, docs/guide/python-passport-ocr.md, docs/guide/python-receipt-ocr.md
=> :memo: Add guides documentation

mindee/client.py, mindee/documents/__init__.py, mindee/documents/financial/__init__.py, mindee/documents/financial/financial_v0.py, mindee/documents/financial/financial_v1.py, tests/__init__.py, tests/documents/test_financial_v0.py, tests/documents/test_financial_v1.py, tests/test_response.py
:sparkles: add support for: financial document v1.
Old financial document renamed to v0.
New unit tests
=> :sparkles: add support for: financial document v1

docs/guide/python-getting-started.md, mindee/cli.py, mindee/client.py, mindee/documents/base.py, mindee/documents/financial/financial_v1.py, mindee/endpoints.py, mindee/input/sources.py, mindee/response.py, tests/test_inputs.py
Add the ability to send an URL to the server.
Added unit tests.
=> :sparkles: add an URL input source

mindee/documents/__init__.py, tests/documents/eu/test_license_plate_v1.py, tests/documents/fr/test_bank_account_details_v1.py, tests/documents/fr/test_carte_grise_v1.py, tests/documents/fr/test_carte_vitale_v1.py, tests/documents/fr/test_id_card_v1.py, tests/documents/test_cropper_v1.py, tests/documents/test_custom_v1.py, tests/documents/test_financial_document_v1.py, tests/documents/test_financial_v1.py, tests/documents/test_passport_v1.py, tests/documents/test_proof_of_address_v1.py, tests/documents/test_receipt_v3.py, tests/documents/test_receipt_v4.py, tests/documents/test_receipt_v5.py, tests/documents/test_shipping_container_v1.py, tests/documents/us/test_bank_check_v1.py
Fix imports for EU documents.
Make sure we use the short import in unit tests to detect this type of problem.
Updated unit tests.
=> :bug: fix EU imports, use short imports in tests

docs/guide/python-cli.md, docs/predictions/standard/international.rst, mindee/cli.py, mindee/client.py, mindee/documents/base.py, mindee/response.py, tests/test_cli.py
- New keyword `parse` in CLI is now required to parse older commands (see the [guide](./docs/guide) for more detail).
- Added support for asynchronous requests in CLI
- Added Invoice Splitter support in CLI (asynchronous)
- Refactored CLI code to accommodate for future additions
- Added keywords `enqueue` and `parse-queued` in CLI
- Fixed InvoiceSplitterV1 auto-documentation page
- Fixed HTTP message display error from `parse_queued` jobs
- Fixed delay calculation for asynchronous job completion
=> Add async CLI support

mindee/documents/financial/financial_document_v1.py, mindee/documents/invoice/invoice_v3.py, mindee/documents/invoice/invoice_v4.py, mindee/documents/receipt/line_item_v5.py, mindee/documents/receipt/receipt_v3.py, mindee/documents/receipt/receipt_v4.py, mindee/documents/receipt/receipt_v5.py, mindee/fields/tax.py, tests/documents/test_financial_document_v1.py, tests/documents/test_invoice_v3.py, tests/documents/test_invoice_v4.py, tests/documents/test_receipt_v3.py, tests/documents/test_receipt_v4.py, tests/fields/test_tax.py
Update printing of receipt, invoice, financial doc as defined by test files.
Unit tests updated as needed.
=> :recycle: update printing of receipt, invoice, financial doc

docs/guide/python-cli.md, mindee/cli.py
When the `-t, --full-text` option is passed to the CLI, print the result of the OCR extraction.
=> :sparkles: add OCR output in CLI

docs/extras/code_samples/bank_account_details_v2.txt, docs/extras/code_samples/invoice_splitter_v1_async.txt, docs/predictions/standard/documents/fr/bank_account_details_v2.rst, docs/predictions/standard/fr.rst, mindee/client.py, mindee/documents/fr/__init__.py, mindee/documents/fr/bank_account_details/bank_account_details_v2.py, mindee/documents/fr/bank_account_details/bank_account_details_v2_bban.py, tests/documents/fr/test_bank_account_details_v2.py
:sparkles: add to support for fr bank account details v2 (autogenerated)
=> :sparkles: add to support for fr bank account details v2

mindee/documents/custom/line_items.py, mindee/geometry.py, tests/documents/test_custom_v1_line_items.py, tests/test_geometry.py
:sparkles: add basic support for line items
(copied from internal library)
New unit tests added.
=> Add line items

mindee/cli.py
Fix for when the product doesn't have the ability to get the OCR response, the CLI response fails.
=> :bug: fix for parsing OCR response in CLI

.github/workflows/test-code-samples.yml, .github/workflows/test.yml, docs/extras/code_samples/petrol_receipts_v1.txt, mindee/cli.py, mindee/client.py, mindee/documents/fr/__init__.py, mindee/documents/fr/petrol_receipt/petrol_receipt_v1.py, mindee/documents/fr/petrol_receipt/petrol_receipt_v1_fuel.py, mindee/documents/fr/petrol_receipt/petrol_receipt_v1_total.py, tests/documents/fr/test_petrol_receipt_v1.py
add support for FR petrol receipts, auto-generated
=> :sparkles: add support for FR petrol receipts

mindee/client.py, mindee/input/sources.py, tests/test_inputs.py
Add a fixing utility to try and delete garbage in PDF headers. Solves _some_ issues with files interpreted as octet streams, and also allows to circumvent errors due to missing file name when giving a temp file.
* Partially addresses #126 
* CI
* Integration testing
=> :test_tube: :sparkles: add **experimental** pdf-fixing utility

docs/extras/code_samples/custom_v1.txt, docs/extras/guide/custom_v1.md, docs/parsing/custom.rst, mindee/error/__init__.py, mindee/error/mindee_error.py, mindee/input/sources.py, mindee/parsing/common/job.py, mindee/parsing/custom/__init__.py, mindee/parsing/custom/classification.py, mindee/parsing/custom/line_items.py, mindee/parsing/custom/list.py, mindee/product/custom/custom_v1_document.py, mindee/product/custom/custom_v1_page.py, tests/product/custom/test_custom_v1_line_items.py, tests/product/custom/test_custom_v1_v2.py
=> :wrench: rework custom internals

README.md, docs/extras/code_samples/custom_v1.txt, docs/extras/guide/custom_v1.md, mindee/cli.py
* :memo: harmonize custom doc sample code
* :bug: custom APIs don't support async mode
=> Misc fixes

.pre-commit-config.yaml
Allow us humans to better control the look of imports.
By adding a trailing comma we can now force to use the multiline layout even if not strictly needed.
This makes it easier to generate code, there was much rejoicing throughout the land.
=> :white_check_mark: better control over import linting

.pre-commit-config.yaml, mindee/input/sources.py, pyproject.toml, setup.cfg, tests/test_inputs.py
Notes: 
- no type declarations for mypy on this lib, unfortunately :/
- Keeping this as draft since licensing isn't fully sorted out.
=> :recycle: replace pikepdf with pypdfium2

mindee/client.py, mindee/input/__init__.py, mindee/input/local_response.py, tests/Input/test_local_response.py, tests/api/test_async_response.py, tests/test_client.py
* :sparkles: add support for webhooks & local responses (with HMAC signature)
=> :sparkles: add webhook support

mindee/input/local_response.py, tests/Input/test_local_response.py
=> :recycle: fix improper test & improper enqueueing for localresponse

mindee/cli.py
Print the full OCR text to console when passing the `-t` argument in CLI.
Not sure why we didn't do this already.
=> :sparkles: support printing the OCR text in the CLI tool

docs/extras/code_samples/default_async.txt, mindee/image_extraction/common/extracted_image.py
=> :memo: fix typos

mindee/image_extraction/common/extracted_image.py, mindee/image_extraction/common/image_extractor.py, tests/image_extraction/test_image_extractor.py
* :recycle: change save format of multi receipts extractor to png
* :memo: fix comment
* :recycle: change save name to have page indices start at 1 for image extractor
=> :recycle: switch default image save format to PNG for image extractor

README.md, docs/extras/guide/custom_v1.md
=> :memo: fix broken documentation URLs

docs/extras/guide/bill_of_lading_v1.md, docs/extras/guide/energy_bill_fra_v1.md, docs/extras/guide/expense_receipts_v5.md, docs/extras/guide/financial_document_v1.md, docs/extras/guide/invoices_v4.md, docs/extras/guide/nutrition_facts_v1.md, docs/extras/guide/payslip_fra_v2.md, docs/extras/guide/us_mail_v2.md, mindee/parsing/standard/date.py, mindee/product/financial_document/financial_document_v1_document.py, mindee/product/invoice/invoice_v4_document.py, tests/fields/test_date.py, tests/product/invoice/test_invoice_v4.py
=> :sparkles: add support for financial document v1.10 & invoice v4.8

CHANGELOG.md, mindee/versions.py
=> :bookmark: Version 4.14.0

.github/workflows/test-code-samples.yml, .github/workflows/test-integration.yml, .github/workflows/test-regression.yml, docs/extras/code_samples/workflow_execution.txt, mindee/__init__.py, mindee/client.py, mindee/input/__init__.py, mindee/input/workflow_options.py, mindee/mindee_http/__init__.py, mindee/mindee_http/base_endpoint.py, mindee/mindee_http/base_settings.py, mindee/mindee_http/endpoint.py, mindee/mindee_http/response_validation.py, mindee/mindee_http/workflow_endpoint.py, mindee/mindee_http/workflow_settings.py, mindee/parsing/common/__init__.py, mindee/parsing/common/execution.py, mindee/parsing/common/execution_file.py, mindee/parsing/common/execution_priority.py, mindee/parsing/common/workflow_response.py, tests/test_code_samples.sh, tests/utils.py, tests/workflows/test_workflow.py, tests/workflows/test_workflow_integration.py
=> :sparkles: add support for workflows

.pre-commit-config.yaml, .pylintrc, mindee/mindee_http/base_settings.py, mindee/versions.py, pyproject.toml
Update pylint, specify minimum versions for build tools.
=> :arrow_up: update pylint

CHANGELOG.md, README.md, docs/extras/guide/custom_v1.md, docs/extras/guide/getting_started.md, mindee/versions.py
=> :bookmark: Version 4.16.0

docs/extras/code_samples/us_mail_v3_async.txt, docs/extras/guide/us_mail_v3.md, docs/product/bill_of_lading_v1.rst, docs/product/ind/indian_passport_v1.rst, docs/product/international_id_v2.rst, docs/product/nutrition_facts_label_v1.rst, docs/product/us/us_mail_v2.rst, docs/product/us/us_mail_v3.rst, mindee/cli.py, mindee/product/us/__init__.py, mindee/product/us/us_mail/__init__.py, mindee/product/us/us_mail/us_mail_v3.py, mindee/product/us/us_mail/us_mail_v3_document.py, mindee/product/us/us_mail/us_mail_v3_recipient_address.py, mindee/product/us/us_mail/us_mail_v3_sender_address.py, tests/product/us/us_mail/test_us_mail_v3.py
=> :sparkles: add support for us mail v3

.github/workflows/tag-version.yml, .pre-commit-config.yaml, docs/product/business_card_v1.rst, docs/product/delivery_note_v1.rst, docs/product/driver_license_v1.rst, docs/product/financial_document_v1.rst, docs/product/fr/energy_bill_v1.rst, docs/product/fr/health_card_v1.rst, docs/product/fr/payslip_v2.rst, docs/product/fr/payslip_v3.rst, docs/product/invoice_v4.rst, docs/product/material_certificate_v1.rst, docs/product/receipt_v5.rst, docs/product/resume_v1.rst, docs/product/us/healthcare_card_v1.rst, mindee/cli.py, mindee/error/mindee_http_error.py, mindee/extraction/pdf_extractor/pdf_extractor.py, tests/product/generated/test_generated_v1.py
=> :art: linting fixes

.github/workflows/_test-integrations.yml, README.md, docs/extras/guide/driver_license_v1.md, docs/extras/guide/financial_document_v1.md, docs/extras/guide/invoices_v4.md, mindee/__init__.py, mindee/product/ind/indian_passport/indian_passport_v1_document.py
=> :recycle: update regression test sample + add quick accessor for LocalResponse

docs/extras/guide/expense_receipts_v5.md, docs/extras/guide/financial_document_v1.md, docs/extras/guide/idcard_fr_v2.md, docs/extras/guide/ind_passport_v1.md, docs/extras/guide/international_id_v2.md, docs/extras/guide/invoice_splitter_v1.md, docs/extras/guide/invoices_v4.md, docs/extras/guide/resume_v1.md, mindee/product/delivery_note/delivery_note_v1_document.py, mindee/product/financial_document/financial_document_v1_document.py, mindee/product/financial_document/financial_document_v1_line_item.py, mindee/product/invoice/invoice_v4_document.py, mindee/product/invoice/invoice_v4_line_item.py, mindee/product/receipt/receipt_v5_document.py, mindee/product/receipt/receipt_v5_line_item.py
=> :memo: update documentation & description on some products

docs/extras/guide/energy_bill_fra_v1.md, mindee/product/fr/energy_bill/energy_bill_v1_document.py, mindee/product/fr/energy_bill/energy_bill_v1_energy_usage.py, mindee/product/fr/energy_bill/energy_bill_v1_meter_detail.py, mindee/product/us/healthcare_card/healthcare_card_v1_document.py
=> :sparkles: bump FR EnergyBillV1 to V1.2 & US HealthcareCardV1 to V1.1

docs/extras/guide/expense_receipts_v5.md, docs/extras/guide/financial_document_v1.md, docs/extras/guide/invoices_v4.md, mindee/client.py
=> :recycle: fix invalid catch mechanism for polling

CHANGELOG.md, mindee/versions.py
=> :bookmark: Version 4.19.0

mindee/parsing/common/document.py
Fix for API returning `null` in extras response.
#312
=> :bug: fix for null objects in extras

CHANGELOG.md, mindee/versions.py
=> :bookmark: Version 4.19.1

docs/extras/code_samples/default_v2.txt, mindee/client_v2.py, mindee/parsing/v2/__init__.py, mindee/parsing/v2/inference_options.py, mindee/parsing/v2/job.py, mindee/parsing/v2/job_response.py, mindee/parsing/v2/raw_text.py, tests/test_client_v2.py
* :recycle: Put `RawText` class in its own file
* :recycle: change `PollingResponse` into `JobResponse` to maintain coherence with other SDKs
* :bug: add missing `created_at` attribute to `Job`
* :recycle: bump test lib
=> :recycle: fix syntaxes for V2, bump test lib

mindee/client_mixin.py, mindee/client_v2.py, mindee/input/inference_predict_options.py, mindee/mindee_http/mindee_api_v2.py, mindee/parsing/v2/inference.py
=> :recycle: minor fixes and tweaks to options and outputs

mindee/parsing/v2/inference_result_fields.py, mindee/parsing/v2/simple_field.py, tests/v2/test_inference_response.py
=> :white_check_mark: update v2 inference tests

mindee/parsing/v2/field/__init__.py, mindee/parsing/v2/field/inference_fields.py, mindee/parsing/v2/field/list_field.py, mindee/parsing/v2/field/object_field.py, mindee/parsing/v2/field/simple_field.py, mindee/parsing/v2/inference_result.py, tests/v2/test_inference_response.py
Harmonize with other libs, add typed accessors to list fields.
=> :sparkles: add list field typed accessors

mindee/geometry/polygon.py, mindee/parsing/standard/base.py, mindee/parsing/standard/position.py, mindee/parsing/v2/field/field_location.py, tests/test_geometry.py, tests/v2/test_inference_response.py
=> :recycle: better polygon init in standard field

.github/workflows/_test-integrations.yml, .github/workflows/_test-regressions.yml, .github/workflows/_test-units.yml, mindee/parsing/v2/field/field_confidence.py, pyproject.toml, tests/v2/test_inference_response.py
Allow comparing field confidence values.
=> :sparkles: allow comparing v2 field confidence
