mindee/mindee-api-python

CHANGELOG.md
mindee/__init__.py
mindee/documents/financial_document.py
mindee/documents/invoice.py
mindee/fields/payment_details.py
setup.py
tests/data/invoices/v2/invoice.json
tests/data/invoices/v2/invoice_all_na.json
tests/documents/test_document.py
tests/documents/test_financial_doc.py
tests/documents/test_invoice.py
tests/fields/test_payment_details.py

Upgrade the version for invoice endpoint to V2
Major changes due to new fields detection and North America support by the invoice endpoint:
* company_number is now a list with many objects for any type of company registration number
* payment_details is now a list of PaymentDetails object, including swift, routing_number, iban and account number
* vat_number was deleted, as it's now part of the company_number
All new code is tested, coverage: 94.14%.

chg: :sparkles: Invoice v2 upgrade

---

mindee/http.py

- [ x] Docs change / refactoring / dependency upgrade

fix: :wastebasket: using new headers format for API token

---

mindee/http.py

- [ x] Bug fix (non-breaking change which fixes an issue)

fix: :bug: forward input_file name when making HTTP request

---

CHANGELOG.md
setup.py

New version
- [X ] My code follows the code style of this project.
- [X ] I have updated the documentation accordingly.

chg: 🔖 prepare v1.2.1

---

.github/workflows/license.yml
.github/workflows/linting.yml
pyproject.toml

Use [`pylic`](https://github.com/ubersan/pylic) in the CI to check for compatible licenses.
Ensure the SDK is compliant with dependencies.
Tested in Github actions.

Add license check

---

mindee-cli.sh
mindee/__main__.py

Add a CLI tool as `__main__.py` for quick debugging and testing.
Useful when we need to run a single file through the SDK for testing mainly.
Also when debugging user issues.

chg: :sparkles: add CLI tool for testing and demo

---

mindee/inputs.py
requirements.txt
setup.py

Update PikePDF and Pillow
#53 
* PikePDF has many bugfixes related to images
* Pillow has CVSS 5.9

Update pikepdf and pillow

---

mindee/__main__.py
mindee/client.py
mindee/documents/base.py
mindee/documents/custom_document.py
mindee/documents/financial_document.py
mindee/documents/invoice.py
mindee/documents/passport.py
mindee/documents/receipt.py
mindee/fields/amount.py
mindee/fields/base.py
mindee/fields/date.py
mindee/fields/locale.py
mindee/fields/orientation.py
mindee/fields/payment_details.py
mindee/fields/tax.py
mindee/http.py
mindee/inputs.py
mindee/versions.py
pyproject.toml

Bunch of small changes for stricter pylint and mypy
We want clean code ;-)

:label: set stricter pylint and mypy settings

---

mindee/fields/locale.py
tests/fields/test_locale.py

If the `language` locale property was not set, no value would be set.

:bug: fix for locale constructor

---

pyproject.toml
requirements.txt
setup.cfg

Loosen setup.py requirements as described here:
https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/
Update `requirements.txt` file in consequence to this.

:arrow_up: loosen setup.py requirements; update pinned dependencies

---

.pre-commit-config.yaml
.pylintrc
docs/Makefile
docs/client.rst
docs/conf.py
docs/documents.rst
docs/field_types.rst
docs/index.rst
docs/make.bat
mindee/client.py
mindee/documents/base.py
mindee/documents/custom_document.py
mindee/documents/financial_document.py
mindee/documents/invoice.py
mindee/documents/passport.py
mindee/documents/receipt.py
mindee/fields/base.py
mindee/fields/date.py
mindee/fields/locale.py
mindee/fields/orientation.py
mindee/fields/payment_details.py
mindee/response.py
setup.cfg
tests/documents/test_financial_doc.py
tests/documents/test_invoice.py
tests/fields/test_field.py

Initial class documentation, to be used as reference.
Also took the opportunity to clean up a bit the code.
Will use this to populate GitHub pages in the future (other PR).
To test locally:
```
pip install -U -e ".[dev,test,docs]"
cd docs
make html
```
Open in your browser file:///PATH/TO/mindee-api-python/docs/_build/html/index.html

Add automated class documentation

---

.pre-commit-config.yaml
mindee/__main__.py
mindee/client.py
mindee/documents/base.py
mindee/documents/custom_document.py
mindee/documents/financial_document.py
mindee/documents/invoice.py
mindee/documents/passport.py
mindee/documents/receipt.py
mindee/fields/amount.py
mindee/fields/base.py
mindee/fields/date.py
mindee/fields/locale.py
mindee/fields/orientation.py
mindee/fields/payment_details.py
mindee/fields/tax.py
mindee/http.py
mindee/inputs.py
pyproject.toml
setup.cfg
tests/test_pkg_versions.py

* update mypy
* add some more typing info
* couple doc fixes

:label: update mypy and add typing info

---

README.md

Fix the documentation link
- [x ] I have read the **CONTRIBUTING** document.

fix Python SDK documentation link

---

.github/workflows/docs.yml
.github/workflows/linting.yml
docs/conf.py

https://mindee.github.io/mindee-api-python/

:memo: publish documentation to pages

---

.github/workflows/docs.yml

:bug: fix for docs action

---

requirements.txt
setup.cfg

:arrow_up: general dependencies upgrade

---

README.md
mindee/geometry.py
tests/test_geometry.py

Functions which are useful for building various tooling on top of.
Some customers have been given these already.
Also, update the link to the API key documentation.
Unit tests added.

Add centroid geometry functions

---

.github/workflows/docs.yml
.github/workflows/publish.yml
setup.cfg

Add automated publishing to Pypi

Add publish

---

mindee/geometry.py
tests/test_geometry.py

Add functions for working with X-axis on word geometry.
Of general interest to all users.

:sparkles: add x-axis geometry functions

---

.github/workflows/docs.yml
.github/workflows/license.yml
.github/workflows/linting.yml
.github/workflows/publish.yml
.github/workflows/test.yml

:construction_worker: test on Windows

---

mindee/__main__.py
mindee/client.py
mindee/documents/__init__.py
mindee/documents/invoice/__init__.py
mindee/documents/invoice/checks.py
mindee/documents/invoice/invoice_v4.py
mindee/documents/invoice/line_item.py
mindee/documents/invoice/reconstruct.py
tests/documents/test_custom_v1.py
tests/documents/test_invoice_v3.py
tests/documents/test_invoice_v4.py

Add support for line items in invoice v4
Added unit tests

:sparkles: Add Invoice V4 (clearer field names, line items)

---

.pre-commit-config.yaml
.pylintrc
examples/display_cropping.py
pyproject.toml

Add an example showing how to display cropper information.

:technologist: add a cropper example

---

mindee/documents/invoice/invoice_v4.py
mindee/documents/receipt/receipt_v4.py

* Add support for Receipt v4.1
* Add support for Invoice v4.1
Unit tests

:sparkles: add support for Receipt v4.1 and Invoice 4.1

---

docs/extras/code_samples/default.txt
tests/test_code_samples.sh

Add a code sample for when there is no client library support.

:white_check_mark: add default code sample

---

mindee/fields/tax.py
tests/documents/test_receipt_v5.py

Fix for tax base value not being picked up.
Added unit test.

:bug: fix for taxe base amount

---

docs/extras/code_samples/material_certificate_v1.txt
docs/predictions/standard/documents/material_certificate_v1.rst
docs/predictions/standard/international.rst
mindee/client.py
mindee/documents/__init__.py
mindee/documents/material_certificate/__init__.py
mindee/documents/material_certificate/material_certificate_v1.py
tests/documents/test_material_certificate_v1.py

**Autogenerated**  add support for material certificate v1

:sparkles: add support for material certificate v1

---

mindee/endpoints.py

add openapi get request, mainly for internal usage

:sparkles: add openapi get request

---

.github/workflows/docs.yml
.github/workflows/license.yml
.github/workflows/linting.yml
.github/workflows/publish.yml
.pre-commit-config.yaml
mindee/documents/passport/passport_v1.py
mindee/input/sources.py
setup.cfg

Fix for `full_name` field when there are multiple given names.

:bug: fix full_name for multiple given names

---

requirements.txt
setup.cfg

update requests to 2.31
https://github.com/mindee/mindee-api-python/security/dependabot/4

:arrow_up: update requests to 2.31

---

requirements.txt

https://github.com/mindee/mindee-api-python/security/dependabot/6

:arrow_up: update all dependencies

---

.pylintrc
docs/extras/code_samples/barcode_reader_v1.txt
docs/extras/code_samples/multi_receipts_detector_v1.txt
docs/extras/code_samples/us_w9_v1.txt
docs/predictions/standard/documents/barcode_reader_v1.rst
docs/predictions/standard/documents/multi_receipts_detector_v1.rst
docs/predictions/standard/documents/us/w9_v1.rst
mindee/cli.py
mindee/client.py
mindee/documents/__init__.py
mindee/documents/barcode_reader/__init__.py
mindee/documents/barcode_reader/barcode_reader_v1.py
mindee/documents/multi_receipts_detector/__init__.py
mindee/documents/multi_receipts_detector/multi_receipts_detector_v1.py
mindee/documents/us/__init__.py
mindee/documents/us/w9/w9_v1.py
mindee/fields/position.py
setup.cfg
tests/documents/test_barcode_reader_v1.py
tests/documents/test_multi_receipts_detector_v1.py
tests/documents/us/test_w9_v1.py

* :sparkles: add support for US W9 V1
* :sparkles: add support for Barcode Reader V1
* :sparkles: add support for Multi Receipts Detector V1

:sparkles: add latest products

---

requirements.txt

* :arrow_up: update dependencies

:arrow_up: upgrade dependencies

---

README.md
docs/guide/cli.md
docs/guide/custom_v1.md

:recycle: v4 update md

---

examples/display_cropping.py
mindee/client.py
mindee/mindee_http/error.py
mindee/parsing/common/api_response.py
tests/mindee_http/test_error.py
tests/test_cli.py
tests/test_client.py

:recycle: update HTTP error handling

---

requirements.txt

* update urllib
* update pillow

:arrow_up: update dependencies

---

docs/extras/code_samples/default_async.txt
tests/test_code_samples.sh

:recycle: add async default code sample

---

.github/workflows/test-code-samples.yml
.github/workflows/test-regression.yml
.github/workflows/unit-test.yml

:test_tube: experimental CI changes

---

mindee/parsing/custom/list.py

:bug: fix custom APIs breaking on missing page id

---

mindee/parsing/common/document.py
tests/api/test_response.py

:sparkles: add n pages attribute to document

---

mindee/parsing/custom/list.py
mindee/parsing/standard/amount.py
mindee/parsing/standard/base.py
mindee/parsing/standard/date.py
mindee/parsing/standard/locale.py
mindee/parsing/standard/payment_details.py
mindee/parsing/standard/position.py
mindee/parsing/standard/text.py

:wrench: fix wrongful instance variable assignments

---

mindee/cli.py

Fix for custom product call in CLI.

:bug: fix for custom product in CLI

---

docs/extras/guide/bank_check_v1.md
docs/extras/guide/cropper_v1.md
docs/extras/guide/idcard_fr_v2.md
docs/extras/guide/invoice_splitter_v1.md
docs/extras/guide/us_driver_license_v1.md
docs/extras/guide/us_w9_v1.md
mindee/client.py
mindee/parsing/common/extras/cropper_extra.py
mindee/parsing/custom/line_items.py
mindee/product/invoice/invoice_v4_line_item.py
mindee/product/invoice_splitter/invoice_splitter_v1_page_group.py
pyproject.toml
tests/api/test_async_response.py
tests/product/custom/test_custom_v1_line_items.py

* :memo: fix typos in some .md docs
* :recycle: fix wrongful assignment in classes
* :recycle: simplify tests

:recycle: typos & fixes

---

docs/extras/code_samples/default_async.txt
mindee/client.py

Fix and improvements for async calls.

:bug: tweak default async config to avoid timeouts

---

mindee/client.py

* Update test resources
* Misc little fixes / improvements to main client

Update test data

---

docs/extras/code_samples/international_id_v1_async.txt
docs/extras/guide/invoice_splitter_v1.md
docs/product/international_id_v1.rst
docs/product/material_certificate_v1.rst
mindee/cli.py
mindee/product/__init__.py
mindee/product/international_id/__init__.py
mindee/product/international_id/international_id_v1.py
mindee/product/international_id/international_id_v1_document.py
mindee/product/invoice/__init__.py
mindee/product/invoice_splitter/__init__.py
mindee/product/material_certificate/material_certificate_v1.py
tests/product/international_id/test_international_id_v1.py

Add a beta version of International ID.
Also harmonize / refactor product imports.

:sparkles: add International ID (beta)

---

docs/extras/guide/custom_v1.md
docs/extras/guide/generated_v1.md

* :memo: fix & clarify the generated v1 documentation

:memo: update generated v1 md

---

.github/workflows/test-regression.yml
.github/workflows/unit-test.yml
.pre-commit-config.yaml
mindee/cli.py
pyproject.toml
setup.cfg
tests/test_pkg_versions.py

* do not run regression tests by default
* update test and lint packages
* have pre-commit handle test and lint packages (except for pylint)

:recycle: do not run regression tests by default; update test and lint packages

---

docs/extras/code_samples/invoices_v4.txt
docs/extras/guide/invoices_v4.md
mindee/parsing/standard/text.py
mindee/product/invoice/invoice_v4_document.py
tests/fields/test_text.py
tests/product/invoice/test_invoice_v4.py

* update invoice API to v4.4, adds `total_tax` field.
* add support for `raw_value` in string fields

:arrow_up: update invoices to v4.4

---

.github/workflows/test-code-samples.yml
docs/extras/guide/generated_v1.md
mindee/parsing/generated/generated_object.py

* :recycle: add additional CI reporting for integration tests
* :memo: fix typos in some documentation

update doc & add integration failure reporting

---

docs/extras/guide/eu_driver_license_v1.md
docs/extras/guide/international_id_v2.md
docs/product/eu/driver_license_v1.rst
mindee/product/eu/driver_license/driver_license_v1.py
mindee/product/eu/driver_license/driver_license_v1_document.py
mindee/product/eu/driver_license/driver_license_v1_page.py

:memo: fix docs

---

mindee/client.py
mindee/error/mindee_http_error.py
mindee/mindee_http/__init__.py
mindee/mindee_http/response_validation.py
mindee/parsing/common/async_predict_response.py
mindee/parsing/common/job.py
mindee/parsing/common/predict_response.py
tests/api/test_async_response.py
tests/mindee_http/test_error.py

:recycle: update error handling

---

mindee/mindee_http/response_validation.py

* :bug: Fix improper handling of error codes as strings in API return (see #227)

:bug: fix invalid error code handling for some errors

---

docs/extras/guide/expense_receipts_v5.md
docs/extras/guide/financial_document_v1.md
docs/extras/guide/invoices_v4.md
docs/extras/guide/material_certificate_v1.md

Fix line-items print syntax & re-add sphyx deleted page

:memo: fix documentation

---

mindee/parsing/standard/company_registration.py

* :recycle: add type on company registration print

:recycle: update company registration display

---

mindee/parsing/standard/amount.py

Fix amount display when value is null for AmountFields

:bug: fix amount display

---

mindee/cli.py

Add entries for Healthcare card & Resume, update financial doc polling method

:recycle: add missing entries to CLI tool

---

setup.cfg

Loosen twine & build pinning to prevent invalid version from blocking releases

:wrench: loosen twine & build pinning

---

docs/extras/code_samples/invoices_v4_async.txt
docs/extras/guide/financial_document_v1.md
docs/extras/guide/invoices_v4.md

* :recycle: add async invoice test file & doc

:recycle: add async invoice call & update doc

---

.github/workflows/docs.yml
.github/workflows/license.yml
.github/workflows/linting.yml
.github/workflows/publish.yml
.github/workflows/test-code-samples.yml
.github/workflows/test-regression.yml
.github/workflows/unit-test.yml

What it says in the description

:wrench: update checkout@v3 to checkout@v4 on all actions

---

docs/extras/guide/expense_receipts_v5.md
docs/extras/guide/financial_document_v1.md
docs/extras/guide/idcard_fr_v2.md
docs/extras/guide/international_id_v2.md
docs/extras/guide/invoices_v4.md
docs/extras/guide/resume_v1.md

* :memo: add classification to guide documentation

:memo: add classification detail to guide documentation

---

.github/workflows/test-integration.yml
mindee/mindee_http/endpoint.py
mindee/parsing/common/document.py
pyproject.toml
tests/extraction/test_invoice_splitter_auto_extraction.py
tests/extras/test_extras_integration.py
tests/extras/test_full_text_ocr.py

* :bug: fix improper handling of full text ocr extra
* :recycle: add integration tests

:bug: fix full text ocr extra not using the proper syntax; add integration tests

---

docs/extras/code_samples/expense_receipts_v5_async.txt
docs/extras/guide/energy_bill_fra_v1.md
docs/extras/guide/expense_receipts_v5.md
docs/extras/guide/financial_document_v1.md
docs/extras/guide/invoices_v4.md

* :memo: add receipt async test file
* :memo: update typos in doc

:memo: update documentation

---

.github/workflows/test-regression.yml

:recycle: update test lib, add workflow notifying

---

.github/workflows/test-regression.yml

:recycle: update test lib & add regression test workflow trigger

---

pyproject.toml

* :arrow_up: loosen pin on requests to allow for up-to-date compatible versions

:arrow_up: loosen pin on requests dependency

---

CHANGELOG.md
mindee/versions.py

:bookmark: Version 4.14.1

---

CHANGELOG.md
mindee/versions.py

:bookmark: Version 4.15.0

---

.github/workflows/tag-version.yml

:sparkles: automatically tag new versions

---

mindee/input/__init__.py
mindee/input/sources/__init__.py
mindee/input/sources/base_64_input.py
mindee/input/sources/bytes_input.py
mindee/input/sources/file_input.py
mindee/input/sources/local_input_source.py
mindee/input/sources/path_input.py
mindee/input/sources/url_input_source.py

:recycle: split up sources module to accomodate for future additions

---

docs/extras/code_samples/workflow_execution.txt

:memo: fix typo in workflow example

---

.github/workflows/docs.yml
.github/workflows/license.yml
.github/workflows/linting.yml
.github/workflows/publish.yml
.github/workflows/test-code-samples.yml
.github/workflows/test-integration.yml
.github/workflows/test-regression.yml
.github/workflows/unit-test.yml

:bug: fix for updated github runners

---

CHANGELOG.md
mindee/versions.py

:bookmark: Version 4.18.0

---

pyproject.toml

See: https://github.com/pypdfium2-team/pypdfium2/issues/336

:arrow_down: downgrade pypdfium due to errors in character readings

---

mindee/product/fr/bank_account_details/__init__.py
mindee/product/fr/id_card/__init__.py
mindee/product/fr/payslip/__init__.py
mindee/product/us/us_mail/__init__.py

:recycle: add missing imports for products with concurrent versions

---

CHANGELOG.md
mindee/versions.py

:bookmark: Version 4.20.0

---

README.md

Add the Python version badge, cuz it's cool.
Open the readme file.

:memo: add compatible python versions

---

CHANGELOG.md
mindee/versions.py

:bookmark: Version 4.21.0

---

docs/extras/code_samples/workflow_ots_rag.txt
tests/test_code_samples.sh

:memo: add sample code for workflow RAG

---

CHANGELOG.md
mindee/versions.py

:bookmark: Version 4.23.0

---

.gitignore
tests/v2/test_inference_response.py

:bug: fix duplicate test method

---

CHANGELOG.md
mindee/versions.py

:bookmark: Version 4.26.0
